### PR TITLE
Create dequeue using circular array

### PR DESCRIPTION
**Pull request by vikasshahu99**
thanks

### CODE REVIEW

**Comment by sskender** [comment]
Hello,

what exactly is this commit?

**Comment by vikasshahu99** [comment]
Meaning of Create dequeue using circular array means
Dequeue means double ended queue
In this queue we can enter elements from front and rear as well as delete.
Hope this helps
Thank you

**Comment by sskender** [comment]
Hello,

thank you, I know what is dequeue. But you did not provide c source file for that data structure, I can not merge that commit.
If you create .c file and place it in queue folder I will be happy to merge that commit.

**Comment by ThuretGbenougan** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
piscui, @ChimiChurro, @renetchi, @johanesm21, @MYYG, @Toormi, @mmacedoeu, @lsgrge, @joicoltrader, @leolianger, @Akin01, @iamravenous, @fichajokers, @harshtrivedi2907, @LuluLiu66, @kotaro88, @Gajack33, @0xOutOfGas, @karimov-javokhir, @stushinov

**Pull request closed without merging**
